#!/bin/bash
#SBATCH --account=hpc1
#SBATCH --partition=general-compute
#SBATCH --qos=general-compute
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=1
#SBATCH --time=00:01:00
#SBATCH --constraint=OPA&CPU-Gold-6130
#SBATCH --exclusive
#SBATCH --job-name="Mandelbrot_4_final"
#SBATCH --output=Mandelbrot_4_final.out
#SBATCH --error=Mandelbrot_4_final%j.err
module load intel/17.0
module load intel-mpi/2017.0.1
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
srun Man_fin.mpi
echo "Add Done!"
